import { IProduct } from "../redux/slices/collection/collection.type";

export const collectionsData: IProduct[] = [
  {
    id: 787,
    mcId: 9002,
    productname: "Men's Thermochromic T-shirt",
    productcode: "NSSM22C-CNT001",
    offer: 50,
    imageurl:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-X.jpg",
    price: 0,
    phone: "admin@nazca.in",
    date: "2022/07/31",
    quantity: "0",
    descpription:
      "Orange special dyed Color Changing crew neck half sleeve Back Graphic T-Shirt",
    descpription1: "T-SHIRTS COLLECTION",
    maincategory: "MEN",
    subcategory: "T-SHIRTS",
    productcolor: "Orange",
    fabric: "HOT",
    minqty: 300,
    deliveryTime: "60",
    sizechart:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/MENS-Crewneck.jpg",
    tax: 5,
    group: "MT",
    productSize: [
      {
        id: 788,
        sid: 12077,
        psize: "S",
        price: 2649,
        sku: "NSSM22C-CNT001-S",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 787,
      },
      {
        id: 789,
        sid: 12078,
        psize: "M",
        price: 2649,
        sku: "NSSM22C-CNT001-M",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 787,
      },
      {
        id: 790,
        sid: 12079,
        psize: "L",
        price: 2649,
        sku: "NSSM22C-CNT001-L",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 787,
      },
      {
        id: 791,
        sid: 12080,
        psize: "XL",
        price: 2649,
        sku: "NSSM22C-CNT001-XL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 787,
      },
      {
        id: 792,
        sid: 12081,
        psize: "2XL",
        price: 2649,
        sku: "NSSM22C-CNT001-2XL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 787,
      },
    ],
    productImages: [
      {
        id: 793,
        imId: 36692,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-1.jpg",
        mcId: 787,
      },
      {
        id: 794,
        imId: 36693,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-2.jpg",
        mcId: 787,
      },
      {
        id: 795,
        imId: 36694,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-3.jpg",
        mcId: 787,
      },
      {
        id: 796,
        imId: 36695,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-4.jpg",
        mcId: 787,
      },
      {
        id: 797,
        imId: 36696,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-5.jpg",
        mcId: 787,
      },
      {
        id: 798,
        imId: 36697,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-6.jpg",
        mcId: 787,
      },
      {
        id: 799,
        imId: 36698,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT001-7.jpg",
        mcId: 787,
      },
    ],
    productSpecs: [
      {
        id: 800,
        spid: 36699,
        specification: "Pattern:Dyed+Print",
        mcId: 787,
      },
      {
        id: 801,
        spid: 36700,
        specification: "Dye:Special Thermochromic dye",
        mcId: 787,
      },
      {
        id: 802,
        spid: 36701,
        specification: "Sleeve:Half Sleeve",
        mcId: 787,
      },
      {
        id: 803,
        spid: 36702,
        specification: "Occasion:Casual Summers",
        mcId: 787,
      },
      {
        id: 804,
        spid: 36703,
        specification: "Fit:Regular Fit",
        mcId: 787,
      },
    ],
    metatags: [
      {
        id: 805,
        mid: 9635,
        description:
          "Men's Thermochromic Print Pink T-shirt : Buy latest Casual Summer Back Printed Round Necked Half Sleeve Pink T-shirt at Nazca With Discount, Regular Fit , Cotton , Graphic Design , Quick Delivery",
        keyword:
          "Mens thermochromic tshirt, Cotton tshirts,Pink tshirt,tshirt, half sleeve tshirts , mens ,tshirt,round neck tshirt , mens roundneck , pick,Thermochromic dye & print , print tshirt , tshirts back print,mens tops,Casual",
        twitter:
          "Mens thermochromic tshirt, Cotton tshirts,Pink tshirt,tshirt, half sleeve tshirts , mens ,tshirt,round neck tshirt , mens roundneck , pick,Thermochromic dye & print , print tshirt , tshirts back print,mens tops,Casual",
        facebook:
          "Mens thermochromic tshirt, Cotton tshirts,Pink tshirt,tshirt, half sleeve tshirts , mens ,tshirt,round neck tshirt , mens roundneck , pick,Thermochromic dye & print , print tshirt , tshirts back print,mens tops,Casual",
        instagram:
          "Mens thermochromic tshirt, Cotton tshirts,Pink tshirt,tshirt, half sleeve tshirts , mens ,tshirt,round neck tshirt , mens roundneck , pick,Thermochromic dye & print , print tshirt , tshirts back print,mens tops,Casual",
        linkedin:
          "Mens thermochromic tshirt, Cotton tshirts,Pink tshirt,tshirt, half sleeve tshirts , mens ,tshirt,round neck tshirt , mens roundneck , pick,Thermochromic dye & print , print tshirt , tshirts back print,mens tops,Casual",
        pintrest:
          "Mens thermochromic tshirt, Cotton tshirts,Pink tshirt,tshirt, half sleeve tshirts , mens ,tshirt,round neck tshirt , mens roundneck , pick,Thermochromic dye & print , print tshirt , tshirts back print,mens tops,Casual",
        mcId: 787,
      },
    ],
    reviews: [],
    ratings: [],
    gsthsn: "",
    subcategory1: "",
    childcategory: "",
    shopbyproducts: "T-SHIRTS",
    pntw: "",
    brand: "",
  },
  {
    id: 806,
    mcId: 9012,
    productname: "Men's CPD T-shirt",
    productcode: "NSSM22C-CLT002",
    offer: 50,
    imageurl:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CLT002-X.jpg",
    price: 0,
    phone: "admin@nazca.in",
    date: "2022/07/31",
    quantity: "0",
    descpription:
      "Red Cold Pigment Dyed trendy look full sleeve Graphic T-Shirt",
    descpription1: "T-SHIRTS COLLECTION",
    maincategory: "MEN",
    subcategory: "T-SHIRTS",
    productcolor: "Red",
    fabric: "",
    minqty: 300,
    deliveryTime: "60",
    sizechart:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/MENS-FULL-SLEEVE.jpg",
    tax: 5,
    group: "MT",
    productSize: [
      {
        id: 807,
        sid: 12082,
        psize: "S",
        price: 1149,
        sku: "NSSM22C-CLT002-S",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 806,
      },
      {
        id: 808,
        sid: 12083,
        psize: "M",
        price: 1149,
        sku: "NSSM22C-CLT002-M",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 806,
      },
      {
        id: 809,
        sid: 12084,
        psize: "L",
        price: 1149,
        sku: "NSSM22C-CLT002-L",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 806,
      },
      {
        id: 810,
        sid: 12085,
        psize: "XL",
        price: 1149,
        sku: "NSSM22C-CLT002-XL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 806,
      },
      {
        id: 811,
        sid: 12086,
        psize: "2XL",
        price: 1149,
        sku: "NSSM22C-CLT002-2XL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 806,
      },
    ],
    productImages: [
      {
        id: 812,
        imId: 36704,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CLT002-1.jpg",
        mcId: 806,
      },
      {
        id: 813,
        imId: 36705,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CLT002-2.jpg",
        mcId: 806,
      },
      {
        id: 814,
        imId: 36706,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CLT002-3.jpg",
        mcId: 806,
      },
      {
        id: 815,
        imId: 36707,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CLT002-4.jpg",
        mcId: 806,
      },
      {
        id: 816,
        imId: 36708,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CLT002-5.jpg",
        mcId: 806,
      },
      {
        id: 817,
        imId: 36709,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CLT002-6.jpg",
        mcId: 806,
      },
      {
        id: 818,
        imId: 36710,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CLT002-7.jpg",
        mcId: 806,
      },
    ],
    productSpecs: [
      {
        id: 819,
        spid: 36711,
        specification: "Pattern:Dyed+Print",
        mcId: 806,
      },
      {
        id: 820,
        spid: 36712,
        specification: "Dye:Special Cold Pigment dye",
        mcId: 806,
      },
      {
        id: 821,
        spid: 36713,
        specification: "Sleeve:Half Sleeve",
        mcId: 806,
      },
      {
        id: 822,
        spid: 36714,
        specification: "Occasion:Casual Summers",
        mcId: 806,
      },
      {
        id: 823,
        spid: 36715,
        specification: "Fit:Regular Fit",
        mcId: 806,
      },
    ],
    metatags: [
      {
        id: 824,
        mid: 9651,
        description:
          "Men's Graphic Full Sleeve T-Shirt : Men's New Arrival at Nazca Full Sleeve Graphic T-Shirt Regular Fit Cotton T-Shirt with Special Cold Pigment Dye",
        keyword:
          "Mens Tshirt, Tshirt , Mens CPD Tshirt, Mens Red Tshirt, Graphic Tshirt , Full Sleeve Tshirt , mens cotton Tshirt, cotton full sleeve Tshirt",
        twitter:
          "Mens Tshirt, Tshirt , Mens CPD Tshirt, Mens Red Tshirt, Graphic Tshirt , Full Sleeve Tshirt , mens cotton Tshirt, cotton full sleeve Tshirt",
        facebook:
          "Mens Tshirt, Tshirt , Mens CPD Tshirt, Mens Red Tshirt, Graphic Tshirt , Full Sleeve Tshirt , mens cotton Tshirt, cotton full sleeve Tshirt",
        instagram:
          "Mens Tshirt, Tshirt , Mens CPD Tshirt, Mens Red Tshirt, Graphic Tshirt , Full Sleeve Tshirt , mens cotton Tshirt, cotton full sleeve Tshirt",
        linkedin:
          "Mens Tshirt, Tshirt , Mens CPD Tshirt, Mens Red Tshirt, Graphic Tshirt , Full Sleeve Tshirt , mens cotton Tshirt, cotton full sleeve Tshirt",
        pintrest:
          "Mens Tshirt, Tshirt , Mens CPD Tshirt, Mens Red Tshirt, Graphic Tshirt , Full Sleeve Tshirt , mens cotton Tshirt, cotton full sleeve Tshirt",
        mcId: 806,
      },
    ],
    reviews: [],
    ratings: [],
    gsthsn: "",
    subcategory1: "",
    childcategory: "",
    shopbyproducts: "T-SHIRTS",
    pntw: "",
    brand: "",
  },
  {
    id: 825,
    mcId: 9022,
    productname: "Men's Tie&Dye T-shirt",
    productcode: "NSSM22C-CNT003",
    offer: 50,
    imageurl:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT003-X.jpg",
    price: 0,
    phone: "admin@nazca.in",
    date: "2022/07/31",
    quantity: "0",
    descpription: "Dark Teal Special Tie Dyed half sleeve Graphic T-Shirt",
    descpription1: "T-SHIRTS COLLECTION",
    maincategory: "MEN",
    subcategory: "T-SHIRTS",
    productcolor: "Dark Teal",
    fabric: "HOT",
    minqty: 300,
    deliveryTime: "60",
    sizechart:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/MENS-Crewneck.jpg",
    tax: 5,
    group: "MT",
    productSize: [
      {
        id: 826,
        sid: 12087,
        psize: "S",
        price: 1149,
        sku: "NSSM22C-CNT003-S",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 825,
      },
      {
        id: 827,
        sid: 12088,
        psize: "M",
        price: 1149,
        sku: "NSSM22C-CNT003-M",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 825,
      },
      {
        id: 828,
        sid: 12089,
        psize: "L",
        price: 1149,
        sku: "NSSM22C-CNT003-L",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 825,
      },
      {
        id: 829,
        sid: 12090,
        psize: "XL",
        price: 1149,
        sku: "NSSM22C-CNT003-XL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 825,
      },
      {
        id: 830,
        sid: 12091,
        psize: "2XL",
        price: 1149,
        sku: "NSSM22C-CNT003-2XL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 825,
      },
    ],
    productImages: [
      {
        id: 831,
        imId: 36716,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT003-1.jpg",
        mcId: 825,
      },
      {
        id: 832,
        imId: 36717,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT003-2.jpg",
        mcId: 825,
      },
      {
        id: 833,
        imId: 36718,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT003-3.jpg",
        mcId: 825,
      },
      {
        id: 834,
        imId: 36719,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT003-4.jpg",
        mcId: 825,
      },
      {
        id: 835,
        imId: 36720,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT003-5.jpg",
        mcId: 825,
      },
      {
        id: 836,
        imId: 36721,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT003-6.jpg",
        mcId: 825,
      },
      {
        id: 837,
        imId: 36722,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT003-7.jpg",
        mcId: 825,
      },
    ],
    productSpecs: [
      {
        id: 838,
        spid: 36723,
        specification: "Pattern:Dyed+Print",
        mcId: 825,
      },
      {
        id: 839,
        spid: 36724,
        specification: "Dye:Tie & Dye",
        mcId: 825,
      },
      {
        id: 840,
        spid: 36725,
        specification: "Sleeve:Half Sleeve",
        mcId: 825,
      },
      {
        id: 841,
        spid: 36726,
        specification: "Occasion:Casual Summers",
        mcId: 825,
      },
      {
        id: 842,
        spid: 36727,
        specification: "Fit:Regular Fit",
        mcId: 825,
      },
    ],
    metatags: [
      {
        id: 843,
        mid: 9647,
        description:
          "Nazca Men's Tie&Dye T-Shirt : Dark Teal Cotton T-shirt , Regular Fit Half Sleeve T-Shirt for Casual Summer wear . Quick Delivery",
        keyword:
          "Mens Tshirt, Mens Tie&Dye Tshirt, Cotton Tshirt, Dark Teal Tshirt,Mens Half Sleeve Tshirt , Half Sleeve Tshirt, Mens Cotton Tshirt, Tie & Dye Tshirt, Tshirt",
        twitter:
          "Mens Tshirt, Mens Tie&Dye Tshirt, Cotton Tshirt, Dark Teal Tshirt,Mens Half Sleeve Tshirt , Half Sleeve Tshirt, Mens Cotton Tshirt, Tie & Dye Tshirt, Tshirt",
        facebook:
          "Mens Tshirt, Mens Tie&Dye Tshirt, Cotton Tshirt, Dark Teal Tshirt,Mens Half Sleeve Tshirt , Half Sleeve Tshirt, Mens Cotton Tshirt, Tie & Dye Tshirt, Tshirt",
        instagram:
          "Mens Tshirt, Mens Tie&Dye Tshirt, Cotton Tshirt, Dark Teal Tshirt,Mens Half Sleeve Tshirt , Half Sleeve Tshirt, Mens Cotton Tshirt, Tie & Dye Tshirt, Tshirt",
        linkedin:
          "Mens Tshirt, Mens Tie&Dye Tshirt, Cotton Tshirt, Dark Teal Tshirt,Mens Half Sleeve Tshirt , Half Sleeve Tshirt, Mens Cotton Tshirt, Tie & Dye Tshirt, Tshirt",
        pintrest:
          "Mens Tshirt, Mens Tie&Dye Tshirt, Cotton Tshirt, Dark Teal Tshirt,Mens Half Sleeve Tshirt , Half Sleeve Tshirt, Mens Cotton Tshirt, Tie & Dye Tshirt, Tshirt",
        mcId: 825,
      },
    ],
    reviews: [],
    ratings: [],
    gsthsn: "",
    subcategory1: "",
    childcategory: "",
    shopbyproducts: "T-SHIRTS",
    pntw: "",
    brand: "",
  },
  {
    id: 1898,
    mcId: 25438,
    productname: "Rustic red henley neck T-shirt",
    productcode: "NSSM22C-HNT048",
    offer: 50,
    imageurl:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-HNT048-X.jpg",
    price: 0,
    phone: "admin@nazca.in",
    date: "2022/07/31",
    quantity: "0",
    descpription:
      "Rustic Red Cold Pigment Dyed short sleeve Henley neck T-Shirt",
    descpription1: "T-SHIRTS COLLECTION",
    maincategory: "MEN",
    subcategory: "T-SHIRTS",
    productcolor: "Rustic Red",
    fabric: "",
    minqty: 300,
    deliveryTime: "60",
    sizechart:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/MENS-Crewneck.jpg",
    tax: 5,
    group: "MT",
    productSize: [
      {
        id: 1899,
        sid: 25516,
        psize: "S",
        price: 1189,
        sku: "NSSM22C-HNT048-S",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1898,
      },
      {
        id: 1900,
        sid: 25517,
        psize: "M",
        price: 1189,
        sku: "NSSM22C-HNT048-M",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1898,
      },
      {
        id: 1901,
        sid: 25518,
        psize: "L",
        price: 1189,
        sku: "NSSM22C-HNT048-L",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1898,
      },
      {
        id: 1902,
        sid: 25519,
        psize: "XL",
        price: 1189,
        sku: "NSSM22C-HNT048-XL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1898,
      },
      {
        id: 1903,
        sid: 25520,
        psize: "XXL",
        price: 1189,
        sku: "NSSM22C-HNT048-XXL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1898,
      },
    ],
    productImages: [
      {
        id: 1904,
        imId: 38109,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-HNT048-1.jpg",
        mcId: 1898,
      },
      {
        id: 1905,
        imId: 38110,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-HNT048-2.jpg",
        mcId: 1898,
      },
      {
        id: 1906,
        imId: 38111,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-HNT048-4.jpg",
        mcId: 1898,
      },
      {
        id: 1907,
        imId: 38112,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-HNT048-5.jpg",
        mcId: 1898,
      },
      {
        id: 1908,
        imId: 38113,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-HNT048-6.jpg",
        mcId: 1898,
      },
    ],
    productSpecs: [
      {
        id: 1909,
        spid: 38114,
        specification: "Pattern:Dyed",
        mcId: 1898,
      },
      {
        id: 1910,
        spid: 38115,
        specification: "Dye:Cold Pigment dye",
        mcId: 1898,
      },
      {
        id: 1911,
        spid: 38116,
        specification: "Sleeve:Half Sleeve",
        mcId: 1898,
      },
      {
        id: 1912,
        spid: 38117,
        specification: "Occasion:Casual Summers",
        mcId: 1898,
      },
      {
        id: 1913,
        spid: 38118,
        specification: "Fit:Regular Fit",
        mcId: 1898,
      },
    ],
    metatags: [
      {
        id: 1914,
        mid: 29291,
        description:
          "Nazca Cotton Rustic Red T-shirt for Men's with Half Sleeve",
        keyword: "Mens, Mentshirt , Red tshirt , Mens Collection , Mens Tees ,",
        twitter: "Mens, Mentshirt , Red tshirt , Mens Collection , Mens Tees",
        facebook: "Mens, Mentshirt , Red tshirt , Mens Collection , Mens Tees",
        instagram: "Mens, Mentshirt , Red tshirt , Mens Collection , Mens Tees",
        linkedin: "Mens, Mentshirt , Red tshirt , Mens Collection , Mens Tees",
        pintrest: "Mens, Mentshirt , Red tshirt , Mens Collection , Mens Tees",
        mcId: 1898,
      },
    ],
    reviews: [],
    ratings: [],
    gsthsn: "6109",
    subcategory1: "",
    childcategory: "",
    shopbyproducts: "T-SHIRTS",
    pntw: "",
    brand: "",
  },
  {
    id: 1915,
    mcId: 25449,
    productname: "Polo T-shirt",
    productcode: "NSSM22C-PTS049",
    offer: 50,
    imageurl:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-PTS049-X.jpg",
    price: 0,
    phone: "admin@nazca.in",
    date: "2022/07/31",
    quantity: "0",
    descpription: "White Rich embroidered Premium airmesh Polo T-Shirt",
    descpription1: "T-SHIRTS COLLECTION",
    maincategory: "MEN",
    subcategory: "T-SHIRTS",
    productcolor: "White",
    fabric: "",
    minqty: 300,
    deliveryTime: "60",
    sizechart:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/MENS-Crewneck.jpg",
    tax: 5,
    group: "MT",
    productSize: [
      {
        id: 1916,
        sid: 25521,
        psize: "S",
        price: 1130,
        sku: "NSSM22C-PTS049-S",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1915,
      },
      {
        id: 1917,
        sid: 25522,
        psize: "M",
        price: 1130,
        sku: "NSSM22C-PTS049-M",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1915,
      },
      {
        id: 1918,
        sid: 25523,
        psize: "L",
        price: 1130,
        sku: "NSSM22C-PTS049-L",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1915,
      },
      {
        id: 1919,
        sid: 25524,
        psize: "XL",
        price: 1130,
        sku: "NSSM22C-PTS049-XL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1915,
      },
      {
        id: 1920,
        sid: 25525,
        psize: "XXL",
        price: 1130,
        sku: "NSSM22C-PTS049-XXL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1915,
      },
    ],
    productImages: [
      {
        id: 1921,
        imId: 26138,
        imageUrl: "",
        mcId: 1915,
      },
      {
        id: 1922,
        imId: 38119,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-PTS049-1.jpg",
        mcId: 1915,
      },
      {
        id: 1923,
        imId: 38120,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-PTS049-2.jpg",
        mcId: 1915,
      },
      {
        id: 1924,
        imId: 38121,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-PTS049-3.jpg",
        mcId: 1915,
      },
      {
        id: 1925,
        imId: 38122,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-PTS049-4.jpg",
        mcId: 1915,
      },
      {
        id: 1926,
        imId: 38123,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-PTS049-5.jpg",
        mcId: 1915,
      },
      {
        id: 1927,
        imId: 38124,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-PTS049-6.jpg",
        mcId: 1915,
      },
    ],
    productSpecs: [
      {
        id: 1928,
        spid: 38125,
        specification: "Pattern:Solid+Logo Embroidery",
        mcId: 1915,
      },
      {
        id: 1929,
        spid: 38126,
        specification: "Sleeve:Half Sleeve",
        mcId: 1915,
      },
      {
        id: 1930,
        spid: 38127,
        specification: "Occasion:Casual Summers",
        mcId: 1915,
      },
      {
        id: 1931,
        spid: 38128,
        specification: "Fit:Regular Fit",
        mcId: 1915,
      },
    ],
    metatags: [],
    reviews: [],
    ratings: [],
    gsthsn: "6109",
    subcategory1: "",
    childcategory: "",
    shopbyproducts: "T-SHIRTS",
    pntw: "",
    brand: "",
  },
  {
    id: 1932,
    mcId: 25460,
    productname: "Grunge Washed T-shirt",
    productcode: "NSSM22C-CNT050",
    offer: 50,
    imageurl:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT050-X.jpg",
    price: 0,
    phone: "admin@nazca.in",
    date: "2022/07/31",
    quantity: "0",
    descpription:
      "Black Special dyed acid washed raglon sleeve crew neck graphic T-Shirt",
    descpription1: "T-SHIRTS COLLECTION",
    maincategory: "MEN",
    subcategory: "T-SHIRTS",
    productcolor: "Black",
    fabric: "HOT",
    minqty: 300,
    deliveryTime: "60",
    sizechart:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/MENS-Crewneck.jpg",
    tax: 5,
    group: "MT",
    productSize: [
      {
        id: 1933,
        sid: 25527,
        psize: "M",
        price: 1197,
        sku: "NSSM22C-CNT050-M",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1932,
      },
      {
        id: 1934,
        sid: 25528,
        psize: "L",
        price: 1197,
        sku: "NSSM22C-CNT050-L",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1932,
      },
      {
        id: 1935,
        sid: 25529,
        psize: "XL",
        price: 1197,
        sku: "NSSM22C-CNT050-XL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1932,
      },
      {
        id: 1936,
        sid: 25530,
        psize: "XXL",
        price: 1197,
        sku: "NSSM22C-CNT050-XXL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1932,
      },
    ],
    productImages: [
      {
        id: 1937,
        imId: 26143,
        imageUrl: "",
        mcId: 1932,
      },
      {
        id: 1938,
        imId: 38129,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT050-1.jpg",
        mcId: 1932,
      },
      {
        id: 1939,
        imId: 38130,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT050-2.jpg",
        mcId: 1932,
      },
      {
        id: 1940,
        imId: 38131,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT050-3.jpg",
        mcId: 1932,
      },
      {
        id: 1941,
        imId: 38132,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT050-4.jpg",
        mcId: 1932,
      },
      {
        id: 1942,
        imId: 38133,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT050-6.jpg",
        mcId: 1932,
      },
    ],
    productSpecs: [
      {
        id: 1943,
        spid: 38134,
        specification: "Pattern:Dyed+Print",
        mcId: 1932,
      },
      {
        id: 1944,
        spid: 38135,
        specification: "Dye:Dyed-Acid Washed",
        mcId: 1932,
      },
      {
        id: 1945,
        spid: 38136,
        specification: "Sleeve:Raglon half sleeve",
        mcId: 1932,
      },
      {
        id: 1946,
        spid: 38137,
        specification: "Occasion:Casual Summers",
        mcId: 1932,
      },
      {
        id: 1947,
        spid: 38138,
        specification: "Fit:Regular Fit",
        mcId: 1932,
      },
    ],
    metatags: [],
    reviews: [],
    ratings: [],
    gsthsn: "6109",
    subcategory1: "",
    childcategory: "",
    shopbyproducts: "T-SHIRTS",
    pntw: "",
    brand: "",
  },
  {
    id: 1998,
    mcId: 26149,
    productname: "Gradient dyed T-Shirt",
    productcode: "NSSM22C-CNT053",
    offer: 50,
    imageurl:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT053-X.jpg",
    price: 0,
    phone: "admin@nazca.in",
    date: "2022/07/31",
    quantity: "0",
    descpription: "Multi color ombre dyed Crew neck short sleeve T-Shirt",
    descpription1: "T-SHIRTS COLLECTION",
    maincategory: "MEN",
    subcategory: "T-SHIRTS",
    productcolor: "Multi",
    fabric: "HOT",
    minqty: 300,
    deliveryTime: "60",
    sizechart:
      "https://nazca-images.s3.ap-south-1.amazonaws.com/products/MENS-Crewneck.jpg",
    tax: 5,
    group: "MT",
    productSize: [
      {
        id: 1999,
        sid: 27283,
        psize: "S",
        price: 1077,
        sku: "NSSM22A-CNT053-S",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1998,
      },
      {
        id: 2000,
        sid: 27284,
        psize: "M",
        price: 1077,
        sku: "NSSM22A-CNT053-M",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1998,
      },
      {
        id: 2001,
        sid: 27285,
        psize: "L",
        price: 1077,
        sku: "NSSM22A-CNT053-L",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1998,
      },
      {
        id: 2002,
        sid: 27286,
        psize: "XL",
        price: 1077,
        sku: "NSSM22A-CNT053-XL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1998,
      },
      {
        id: 2003,
        sid: 27287,
        psize: "XXL",
        price: 1077,
        sku: "NSSM22A-CNT053-XXL",
        qty: 0,
        length: 0,
        width: 0,
        height: 0,
        mcId: 1998,
      },
    ],
    productImages: [
      {
        id: 2004,
        imId: 38139,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT053-1.jpg",
        mcId: 1998,
      },
      {
        id: 2005,
        imId: 38140,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT053-2.jpg",
        mcId: 1998,
      },
      {
        id: 2006,
        imId: 38141,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT053-3.jpg",
        mcId: 1998,
      },
      {
        id: 2007,
        imId: 38142,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT053-4.jpg",
        mcId: 1998,
      },
      {
        id: 2008,
        imId: 38143,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT053-5.jpg",
        mcId: 1998,
      },
      {
        id: 2009,
        imId: 38144,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT053-6.jpg",
        mcId: 1998,
      },
      {
        id: 2010,
        imId: 38145,
        imageUrl:
          "https://nazca-images.s3.ap-south-1.amazonaws.com/products/NSSM22C-CNT053-7.jpg",
        mcId: 1998,
      },
    ],
    productSpecs: [
      {
        id: 2011,
        spid: 38146,
        specification: "Pattern:Dyed+Print",
        mcId: 1998,
      },
      {
        id: 2012,
        spid: 38147,
        specification: "Dye:Multi color Ombre Dyed",
        mcId: 1998,
      },
      {
        id: 2013,
        spid: 38148,
        specification: "Sleeve:Half Sleeve",
        mcId: 1998,
      },
      {
        id: 2014,
        spid: 38149,
        specification: "Occasion:Casual Summers",
        mcId: 1998,
      },
      {
        id: 2015,
        spid: 38150,
        specification: "Fit:Regular Fit",
        mcId: 1998,
      },
    ],
    metatags: [],
    reviews: [],
    ratings: [],
    gsthsn: "6109",
    subcategory1: "",
    childcategory: "",
    shopbyproducts: "T-SHIRTS",
    pntw: "",
    brand: "",
  },
];
